version: '3.7'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:

  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_HOST=${DB_HOST}
      - TZ=Asia/Seoul

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    command: "/bin/sh -c 'nginx; trap exit TERM; while :; do sleep 6h  & wait $${!}; nginx -s reload; done;'"

volumes:
  mysql-data:
